##### BEGIN image.base/Dockerfile/image-header #####
FROM vcwebio/conteco.image.wrapper AS wrapper
FROM vcwebio/conteco.external.journalbeat:7.9.2 AS base
##### END image.base/Dockerfile/image-header #####

##### BEGIN image.base/Dockerfile/conteco #####
COPY --from=wrapper /conteco/ /conteco/
ENTRYPOINT ["/conteco/bin/image/wrapper/entrypoint"]
##### END image.base/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/conteco #####
COPY ./conteco/ /conteco/
RUN rm -rf /conteco/repo
COPY ./ /conteco/repo/
RUN chmod -R 555 /conteco
##### END image/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/build-instructions #####
ENV CONTECO_ENTRYPOINT "/conteco/bin/journalbeat/base/docker-entrypoint"
COPY ./conteco/configs/usr/share/journalbeat/journalbeat.yml /usr/share/journalbeat/journalbeat.yml
#USER journalbeat
##### END image/Dockerfile/build-instructions #####

##### BEGIN image.base/Dockerfile/env-labels-footer #####
ENV CONTECO_REALM="vcwebio" \
    CONTECO_ECOSYSTEM="conteco" \
    CONTECO_TYPE="journalbeat" \
    CONTECO_NAME="sasl" \
    CONTECO_TAG="7.9.2" \
    CONTECO_BASE="external.journalbeat:7.9.2" \
    CONTECO_BUILD="image-base"
LABEL io.vcweb.schema-version="1.0" \
      io.vcweb.realm="vcwebio" \
      io.vcweb.ecosystem="conteco" \
      io.vcweb.type="journalbeat" \
      io.vcweb.name="sasl" \
      io.vcweb.tag="7.9.2" \
      io.vcweb.base="external.journalbeat:7.9.2" \
      io.vcweb.build="image-base" \
      io.vcweb.label="journalbeat.sasl - ContEco" \
      io.vcweb.description="Journalbeat image for sasl output, with templated default configuration." \
      io.vcweb.docker.cmd.help="docker run vcwebio/conteco.journalbeat.sasl --help"
##### END image.base/Dockerfile/env-labels-footer #####
